name: msatk
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.10,<3.13
  - biopython
  - pandas
  - numpy
  - scipy
  - matplotlib-base
  - jinja2
  - typer
  - rich
  - pydantic
  - pip
  - pip:
      - msatk
